/*MAGNETOMETER.H
        Created on: Dec 03, 2024
        Authors: Ximena Zepeda and Claudio Morales
*/
#include "MAGNETOMETER.h"
#include<stdint.h>
#include<stdbool.h>


void magnetometer_init(void){
    uint8_t LECTURE = I2C_READ(MAGNETOMETER_I2C_ADDRESS, CONF_REGISTER_A);
    LECTURE = LECTURE&0x00 + 0xF0;
    I2C_WRITE(MAGNETOMETER_I2C_ADDRESS, LECTURE, CONF_REGISTER_A);
    //CONF_REGISTER_B
    uint8_t LECTURE = I2C_READ(MAGNETOMETER_I2C_ADDRESS, CONF_REGISTER_B);
    LECTURE = LECTURE&0x00 + 0x20;
    I2C_WRITE(MAGNETOMETER_I2C_ADDRESS, LECTURE, CONF_REGISTER_B);
    //MODE_REGISTER_READ_OR_WRITE
    uint8_t LECTURE = I2C_READ(MAGNETOMETER_I2C_ADDRESS, MODE_REGISTER_READ_OR_WRITE);
    LECTURE = LECTURE&0x00 + 0x80;
    I2C_WRITE(MAGNETOMETER_I2C_ADDRESS, LECTURE, MODE_REGISTER_READ_OR_WRITE);
    //STATUS_REGISTER
    // uint8_t LECTURE = I2C_READ(MAGNETOMETER_I2C_ADDRESS, STATUS_REGISTER);
    // LECTURE = LECTURE&0x00 + 0x80;
    // I2C_WRITE(MAGNETOMETER_I2C_ADDRESS, LECTURE, STATUS_REGISTER);
    //MODE_REGISTER_READ_OR_WRITE
}

void magnetometer_read(float * MAGNETOMETER_COOKED){
    uint8_t MAGNETOMETER_RAW[6];
    MAGNETOMETER_RAW[0] = I2C_READ(MAGNETOMETER_I2C_ADDRESS, DATA_OUTPUT_X_MSB_REGISTER);
    MAGNETOMETER_RAW[1] = I2C_READ(MAGNETOMETER_I2C_ADDRESS, DATA_OUTPUT_X_LSB_REGISTER);
    MAGNETOMETER_RAW[2] = I2C_READ(MAGNETOMETER_I2C_ADDRESS, DATA_OUTPUT_Z_MSB_REGISTER);
    MAGNETOMETER_RAW[3] = I2C_READ(MAGNETOMETER_I2C_ADDRESS, DATA_OUTPUT_Z_LSB_REGISTER);
    MAGNETOMETER_RAW[4] = I2C_READ(MAGNETOMETER_I2C_ADDRESS, DATA_OUTPUT_Y_MSB_REGISTER);
    MAGNETOMETER_RAW[5] = I2C_READ(MAGNETOMETER_I2C_ADDRESS, DATA_OUTPUT_Y_LSB_REGISTER);

    int16_t MAGNETOMETER[3];
    MAGNETOMETER[0]= MAGNETOMETER_RAW[0] << 8 + MAGNETOMETER_RAW[1];
    MAGNETOMETER[1]= MAGNETOMETER_RAW[2] << 8 + MAGNETOMETER_RAW[3];
    MAGNETOMETER[2]= MAGNETOMETER_RAW[4] << 8 + MAGNETOMETER_RAW[5];

    MAGNETOMETER_COOKED[0] = (float)MAGNETOMETER[0];
    MAGNETOMETER_COOKED[1] = (float)MAGNETOMETER[1];
    MAGNETOMETER_COOKED[2] = (float)MAGNETOMETER[2];
}

